title: 'healeyj.github.io'
description: "A jekyll theme inspired by linux consoles for hackers, developers and script kiddies."
baseurl: "/"
url: "https://healeyj.github.io"

header_pages:
  - index.md
  - portfolio.md

style: dark

footer: 'connect with me on <a href="https://www.linkedin.com/in/healey-joseph/">LinkedIn</a><br /><div data-iframe-width="150" data-iframe-height="270" data-share-badge-id="35f828e5-a950-41b5-bd90-21b240850769" data-share-badge-host="https://www.credly.com"></div><script type="text/javascript" async src="//cdn.credly.com/assets/utilities/embed.js"></script>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
